In [1]:
import pandas as pd
import numpy as np

# Importing data

In [2]:
SnpSiftData=pd.read_csv(r'data/snpsiftdata.tab',delimiter='\t',encoding='UTF-8')
chromosome_name=pd.read_csv(r'data/chromosome_name_mapping.tab',delimiter='\t',encoding='UTF-8')
Genotype_Data=pd.read_csv(r'data/genotype_data.tab',delimiter='\t',encoding='UTF-8')
passport=pd.read_csv(r'data/passport.tab',delimiter='\t',encoding='UTF-8')

In [11]:
passport.replace(np.NaN,'NA',inplace=True)
passport

   Sample-ID Plant-ID Branch-ID  Variety Generation Treatment Dose
0       1-C7       NA        NA  Venetia         M0        NA   NA
1       1-D4       NA        NA  Venetia         M0        NA   NA
2       1-E2       NA        NA  Venetia         M0        NA   NA
3       1-E4       NA        NA  Venetia         M0        NA   NA
4      15-A5       NA        NA  Caturra         M0        NA   NA
5      15-A7       NA        NA  Caturra         M0        NA   NA
6      15-B2       NA        NA  Caturra         M0        NA   NA
7      15-C2       NA        NA   Catuai         M0        NA   NA
8      15-D6       NA        NA  Caturra         M0        NA   NA
9      16-C5       NA        NA   Catuai         M0        NA   NA
10     16-D7       NA        NA   Catuai         M0        NA   NA
11     16-E4       NA        NA   Catuai         M0        NA   NA

In [3]:
Genotype_Data_1=pd.melt(Genotype_Data,id_vars=['CHROM','POS'],var_name='Sample_ID',value_name='GT')
Genotype_Data_1

               CHROM       POS Sample_ID   GT
0        NC_008535.1     18596      1-C7  0/1
1        NC_008535.1     18671      1-C7  0/1
2        NC_008535.1     18699      1-C7  0/1
3        NC_008535.1     18709      1-C7  0/0
4        NC_008535.1     18753      1-C7  0/1
...              ...       ...       ...  ...
3968671  NC_039919.1  42295525     16-E4  0/1
3968672  NC_039919.1  42295648     16-E4  0/1
3968673  NC_039919.1  42307975     16-E4  0/0
3968674  NC_039919.1  42330783     16-E4  0/0
3968675  NC_039919.1  42341115     16-E4  0/1

[3968676 rows x 4 columns]

# Adding a unique column based on Chromosome name and Position in both the Genotype_Data_1 file and SnpSiftData file

In [4]:
Genotype_Data_1['Chrom_Pos']=Genotype_Data_1['CHROM'].astype(str).str.cat(Genotype_Data_1['POS'].astype(str),sep='_')
Genotype_Data_1

               CHROM       POS Sample_ID   GT             Chrom_Pos
0        NC_008535.1     18596      1-C7  0/1     NC_008535.1_18596
1        NC_008535.1     18671      1-C7  0/1     NC_008535.1_18671
2        NC_008535.1     18699      1-C7  0/1     NC_008535.1_18699
3        NC_008535.1     18709      1-C7  0/0     NC_008535.1_18709
4        NC_008535.1     18753      1-C7  0/1     NC_008535.1_18753
...              ...       ...       ...  ...                   ...
3968671  NC_039919.1  42295525     16-E4  0/1  NC_039919.1_42295525
3968672  NC_039919.1  42295648     16-E4  0/1  NC_039919.1_42295648
3968673  NC_039919.1  42307975     16-E4  0/0  NC_039919.1_42307975
3968674  NC_039919.1  42330783     16-E4  0/0  NC_039919.1_42330783
3968675  NC_039919.1  42341115     16-E4  0/1  NC_039919.1_42341115

[3968676 rows x 5 columns]

In [5]:
SnpSiftData['Chrom_Pos']=SnpSiftData['CHROM'].astype(str).str.cat(SnpSiftData['POS'].astype(str),sep='_')
SnpSiftData

,ANN[*].GENE,ANN[*].DISTANCE,CHROM,POS,ID,REF,ALT,TYPE,ANN[*].IMPACT,ANN[*].EFFECT,ANN[*].FEATURE,ANN[*].FEATUREID,ANN[*].BIOTYPE,ANN[*].RANK,Chrom_Pos
0,rpoC2,0,NC_008535.1,18596,NaN,CT,TC,complex,MODERATE,missense_variant,transcript,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596
1,atpH,4688,NC_008535.1,18596,NaN,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp008,protein_coding,-1,NC_008535.1_18596
2,atpI,2904,NC_008535.1,18596,NaN,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp009,protein_coding,-1,NC_008535.1_18596
3,rps2,1960,NC_008535.1,18596,NaN,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp010,protein_coding,-1,NC_008535.1_18596
4,rpoC1,2575,NC_008535.1,18596,NaN,CT,TC,complex,MODIFIER,downstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp012,protein_coding,-1,NC_008535.1_18596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2312683,exon-XR_003454739.1-1,0,NC_039919.1,42341115,NaN,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,intron_variant,transcript,rna-XR_003454739.1,pseudogene,1,NC_039919.1_42341115
2312684,LOC113719066,0,NC_039919.1,42341115,NaN,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XM_027244072.1,protein_coding,-1,NC_039919.1_42341115
2312685,LOC113719066,0,NC_039919.1,42341115,NaN,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XM_027244072.1,protein_coding,-1,NC_039919.1_42341115
2312686,LOC113719066,0,NC_039919.1,42341115,NaN,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115
2312687,LOC113719066,0,NC_039919.1,42341115,NaN,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115

# Adding the information {Variety, Generation} from the passport file into Genotype_Data_1 file.

In [6]:
Genotype_Data_1.insert(4,'Variety',Genotype_Data_1['Sample_ID'].map(passport.set_index('Sample-ID')['Variety']))
Genotype_Data_1

               CHROM       POS Sample_ID   GT  Variety             Chrom_Pos
0        NC_008535.1     18596      1-C7  0/1  Venetia     NC_008535.1_18596
1        NC_008535.1     18671      1-C7  0/1  Venetia     NC_008535.1_18671
2        NC_008535.1     18699      1-C7  0/1  Venetia     NC_008535.1_18699
3        NC_008535.1     18709      1-C7  0/0  Venetia     NC_008535.1_18709
4        NC_008535.1     18753      1-C7  0/1  Venetia     NC_008535.1_18753
...              ...       ...       ...  ...      ...                   ...
3968671  NC_039919.1  42295525     16-E4  0/1   Catuai  NC_039919.1_42295525
3968672  NC_039919.1  42295648     16-E4  0/1   Catuai  NC_039919.1_42295648
3968673  NC_039919.1  42307975     16-E4  0/0   Catuai  NC_039919.1_42307975
3968674  NC_039919.1  42330783     16-E4  0/0   Catuai  NC_039919.1_42330783
3968675  NC_039919.1  42341115     16-E4  0/1   Catuai  NC_039919.1_42341115

[3968676 rows x 6 columns]

In [7]:
Genotype_Data_1.insert(5,'Generation',Genotype_Data_1['Sample_ID'].map(passport.set_index('Sample-ID')['Generation']))
Genotype_Data_1

,CHROM,POS,Sample_ID,GT,Variety,Generation,Chrom_Pos
0,NC_008535.1,18596,1-C7,0/1,Venetia,M0,NC_008535.1_18596
1,NC_008535.1,18671,1-C7,0/1,Venetia,M0,NC_008535.1_18671
2,NC_008535.1,18699,1-C7,0/1,Venetia,M0,NC_008535.1_18699
3,NC_008535.1,18709,1-C7,0/0,Venetia,M0,NC_008535.1_18709
4,NC_008535.1,18753,1-C7,0/1,Venetia,M0,NC_008535.1_18753
...,...,...,...,...,...,...,...
3968671,NC_039919.1,42295525,16-E4,0/1,Catuai,M0,NC_039919.1_42295525
3968672,NC_039919.1,42295648,16-E4,0/1,Catuai,M0,NC_039919.1_42295648
3968673,NC_039919.1,42307975,16-E4,0/0,Catuai,M0,NC_039919.1_42307975
3968674,NC_039919.1,42330783,16-E4,0/0,Catuai,M0,NC_039919.1_42330783
3968675,NC_039919.1,42341115,16-E4,0/1,Catuai,M0,NC_039919.1_42341115

In [8]:
Genotype_Data_1.insert(5,'Treatment',Genotype_Data_1['Sample_ID'].map(passport.set_index('Sample-ID')['Treatment']))
Genotype_Data_1

,CHROM,POS,Sample_ID,GT,Variety,Treatment,Generation,Chrom_Pos
0,NC_008535.1,18596,1-C7,0/1,Venetia,NaN,M0,NC_008535.1_18596
1,NC_008535.1,18671,1-C7,0/1,Venetia,NaN,M0,NC_008535.1_18671
2,NC_008535.1,18699,1-C7,0/1,Venetia,NaN,M0,NC_008535.1_18699
3,NC_008535.1,18709,1-C7,0/0,Venetia,NaN,M0,NC_008535.1_18709
4,NC_008535.1,18753,1-C7,0/1,Venetia,NaN,M0,NC_008535.1_18753
...,...,...,...,...,...,...,...,...
3968671,NC_039919.1,42295525,16-E4,0/1,Catuai,NaN,M0,NC_039919.1_42295525
3968672,NC_039919.1,42295648,16-E4,0/1,Catuai,NaN,M0,NC_039919.1_42295648
3968673,NC_039919.1,42307975,16-E4,0/0,Catuai,NaN,M0,NC_039919.1_42307975
3968674,NC_039919.1,42330783,16-E4,0/0,Catuai,NaN,M0,NC_039919.1_42330783
3968675,NC_039919.1,42341115,16-E4,0/1,Catuai,NaN,M0,NC_039919.1_42341115

In [9]:
Genotype_Data_1.insert(5,'Dose',Genotype_Data_1['Sample_ID'].map(passport.set_index('Sample-ID')['Dose']))
Genotype_Data_1

,CHROM,POS,Sample_ID,GT,Variety,Dose,Treatment,Generation,Chrom_Pos
0,NC_008535.1,18596,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18596
1,NC_008535.1,18671,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18671
2,NC_008535.1,18699,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18699
3,NC_008535.1,18709,1-C7,0/0,Venetia,NaN,NaN,M0,NC_008535.1_18709
4,NC_008535.1,18753,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18753
...,...,...,...,...,...,...,...,...,...
3968671,NC_039919.1,42295525,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42295525
3968672,NC_039919.1,42295648,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42295648
3968673,NC_039919.1,42307975,16-E4,0/0,Catuai,NaN,NaN,M0,NC_039919.1_42307975
3968674,NC_039919.1,42330783,16-E4,0/0,Catuai,NaN,NaN,M0,NC_039919.1_42330783
3968675,NC_039919.1,42341115,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42341115

# Adding the chromosome names from the chromosome_name file.(Note the names will the same at first but if the user updates them they will be updated)

In [10]:
SnpSiftData.insert(5,'chrome_name',SnpSiftData['CHROM'].map(chromosome_name.set_index('Contig')['Chromosome']))
SnpSiftData

,ANN[*].GENE,ANN[*].DISTANCE,CHROM,POS,ID,chrome_name,REF,ALT,TYPE,ANN[*].IMPACT,ANN[*].EFFECT,ANN[*].FEATURE,ANN[*].FEATUREID,ANN[*].BIOTYPE,ANN[*].RANK,Chrom_Pos
0,rpoC2,0,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODERATE,missense_variant,transcript,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596
1,atpH,4688,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp008,protein_coding,-1,NC_008535.1_18596
2,atpI,2904,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp009,protein_coding,-1,NC_008535.1_18596
3,rps2,1960,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp010,protein_coding,-1,NC_008535.1_18596
4,rpoC1,2575,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,downstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp012,protein_coding,-1,NC_008535.1_18596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2312683,exon-XR_003454739.1-1,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,intron_variant,transcript,rna-XR_003454739.1,pseudogene,1,NC_039919.1_42341115
2312684,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XM_027244072.1,protein_coding,-1,NC_039919.1_42341115
2312685,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XM_027244072.1,protein_coding,-1,NC_039919.1_42341115
2312686,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115
2312687,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115

In [11]:
SnpSiftData.rename(columns={'CHROM': 'CONTIG', 'chrome_name':'CHROM'}, inplace=True)
SnpSiftData

,ANN[*].GENE,ANN[*].DISTANCE,CONTIG,POS,ID,CHROM,REF,ALT,TYPE,ANN[*].IMPACT,ANN[*].EFFECT,ANN[*].FEATURE,ANN[*].FEATUREID,ANN[*].BIOTYPE,ANN[*].RANK,Chrom_Pos
0,rpoC2,0,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODERATE,missense_variant,transcript,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596
1,atpH,4688,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp008,protein_coding,-1,NC_008535.1_18596
2,atpI,2904,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp009,protein_coding,-1,NC_008535.1_18596
3,rps2,1960,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,upstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp010,protein_coding,-1,NC_008535.1_18596
4,rpoC1,2575,NC_008535.1,18596,NaN,Chloroplast,CT,TC,complex,MODIFIER,downstream_gene_variant,transcript,TRANSCRIPT_gene-CoarCp012,protein_coding,-1,NC_008535.1_18596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2312683,exon-XR_003454739.1-1,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,intron_variant,transcript,rna-XR_003454739.1,pseudogene,1,NC_039919.1_42341115
2312684,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XM_027244072.1,protein_coding,-1,NC_039919.1_42341115
2312685,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XM_027244072.1,protein_coding,-1,NC_039919.1_42341115
2312686,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115
2312687,LOC113719066,0,NC_039919.1,42341115,NaN,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,transcript,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115

In [12]:
Genotype_Data_1.insert(1, 'chrome_name', Genotype_Data_1['CHROM'].map(chromosome_name.set_index('Contig')['Chromosome']))
Genotype_Data_1

,CHROM,chrome_name,POS,Sample_ID,GT,Variety,Dose,Treatment,Generation,Chrom_Pos
0,NC_008535.1,Chloroplast,18596,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18596
1,NC_008535.1,Chloroplast,18671,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18671
2,NC_008535.1,Chloroplast,18699,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18699
3,NC_008535.1,Chloroplast,18709,1-C7,0/0,Venetia,NaN,NaN,M0,NC_008535.1_18709
4,NC_008535.1,Chloroplast,18753,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18753
...,...,...,...,...,...,...,...,...,...,...
3968671,NC_039919.1,Chr11e,42295525,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42295525
3968672,NC_039919.1,Chr11e,42295648,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42295648
3968673,NC_039919.1,Chr11e,42307975,16-E4,0/0,Catuai,NaN,NaN,M0,NC_039919.1_42307975
3968674,NC_039919.1,Chr11e,42330783,16-E4,0/0,Catuai,NaN,NaN,M0,NC_039919.1_42330783
3968675,NC_039919.1,Chr11e,42341115,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42341115

In [13]:
Genotype_Data_1.rename(columns={'CHROM': 'CONTIG', 'chrome_name':'CHROM'}, inplace=True)
Genotype_Data_1

,CONTIG,CHROM,POS,Sample_ID,GT,Variety,Dose,Treatment,Generation,Chrom_Pos
0,NC_008535.1,Chloroplast,18596,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18596
1,NC_008535.1,Chloroplast,18671,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18671
2,NC_008535.1,Chloroplast,18699,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18699
3,NC_008535.1,Chloroplast,18709,1-C7,0/0,Venetia,NaN,NaN,M0,NC_008535.1_18709
4,NC_008535.1,Chloroplast,18753,1-C7,0/1,Venetia,NaN,NaN,M0,NC_008535.1_18753
...,...,...,...,...,...,...,...,...,...,...
3968671,NC_039919.1,Chr11e,42295525,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42295525
3968672,NC_039919.1,Chr11e,42295648,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42295648
3968673,NC_039919.1,Chr11e,42307975,16-E4,0/0,Catuai,NaN,NaN,M0,NC_039919.1_42307975
3968674,NC_039919.1,Chr11e,42330783,16-E4,0/0,Catuai,NaN,NaN,M0,NC_039919.1_42330783
3968675,NC_039919.1,Chr11e,42341115,16-E4,0/1,Catuai,NaN,NaN,M0,NC_039919.1_42341115

In [14]:
Genotype_Data_1.replace(np.NaN,'NA',inplace=True)
SnpSiftData.replace(np.NaN, 'NA', inplace=True)

In [15]:
master = pd.merge(SnpSiftData, Genotype_Data_1)
master

,ANN[*].GENE,ANN[*].DISTANCE,CONTIG,POS,ID,CHROM,REF,ALT,TYPE,ANN[*].IMPACT,...,ANN[*].FEATUREID,ANN[*].BIOTYPE,ANN[*].RANK,Chrom_Pos,Sample_ID,GT,Variety,Dose,Treatment,Generation
0,rpoC2,0,NC_008535.1,18596,NA,Chloroplast,CT,TC,complex,MODERATE,...,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596,1-C7,0/1,Venetia,NA,NA,M0
1,rpoC2,0,NC_008535.1,18596,NA,Chloroplast,CT,TC,complex,MODERATE,...,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596,1-D4,0/1,Venetia,NA,NA,M0
2,rpoC2,0,NC_008535.1,18596,NA,Chloroplast,CT,TC,complex,MODERATE,...,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596,1-E2,0/1,Venetia,NA,NA,M0
3,rpoC2,0,NC_008535.1,18596,NA,Chloroplast,CT,TC,complex,MODERATE,...,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596,1-E4,0/1,Venetia,NA,NA,M0
4,rpoC2,0,NC_008535.1,18596,NA,Chloroplast,CT,TC,complex,MODERATE,...,TRANSCRIPT_gene-CoarCp011,protein_coding,1,NC_008535.1_18596,15-A5,0/0,Caturra,NA,NA,M0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27752251,LOC113719066,0,NC_039919.1,42341115,NA,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,...,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115,15-C2,0/1,Catuai,NA,NA,M0
27752252,LOC113719066,0,NC_039919.1,42341115,NA,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,...,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115,15-D6,0/1,Caturra,NA,NA,M0
27752253,LOC113719066,0,NC_039919.1,42341115,NA,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,...,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115,16-C5,0/2,Catuai,NA,NA,M0
27752254,LOC113719066,0,NC_039919.1,42341115,NA,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,...,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115,16-D7,0/2,Catuai,NA,NA,M0
27752255,LOC113719066,0,NC_039919.1,42341115,NA,Chr11e,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,...,XR_003454739.1,pseudogene,-1,NC_039919.1_42341115,16-E4,0/1,Catuai,NA,NA,M0

In [25]:
(master['ANN[*].FEATURE'] == 'transcript').count()

27752256

In [16]:
cols = master.columns.tolist()
cols

['ANN[*].GENE',
 'ANN[*].DISTANCE',
 'CONTIG',
 'POS',
 'ID',
 'CHROM',
 'REF',
 'ALT',
 'TYPE',
 'ANN[*].IMPACT',
 'ANN[*].EFFECT',
 'ANN[*].FEATURE',
 'ANN[*].FEATUREID',
 'ANN[*].BIOTYPE',
 'ANN[*].RANK',
 'Chrom_Pos',
 'Sample_ID',
 'GT',
 'Variety',
 'Dose',
 'Treatment',
 'Generation']

In [26]:
new_col_order = [
    'ANN[*].GENE',
    'CHROM',
    'CONTIG',
    'POS',
    'Sample_ID',
    'Variety',
    'Generation',
    'Treatment',
    'Dose',
    'GT',
    'REF',
    'ALT',
    'TYPE',
    'ANN[*].IMPACT',
    'ANN[*].EFFECT',
    'ANN[*].FEATUREID',
    'ANN[*].BIOTYPE',
    'ANN[*].DISTANCE',
    'ID'   
]

In [27]:
master_final = master[new_col_order]

In [29]:
master_final

,ANN[*].GENE,CHROM,CONTIG,POS,Sample_ID,Variety,Generation,Treatment,Dose,GT,REF,ALT,TYPE,ANN[*].IMPACT,ANN[*].EFFECT,ANN[*].FEATUREID,ANN[*].BIOTYPE,ANN[*].DISTANCE,ID
0,rpoC2,Chloroplast,NC_008535.1,18596,1-C7,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
1,rpoC2,Chloroplast,NC_008535.1,18596,1-D4,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
2,rpoC2,Chloroplast,NC_008535.1,18596,1-E2,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
3,rpoC2,Chloroplast,NC_008535.1,18596,1-E4,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
4,rpoC2,Chloroplast,NC_008535.1,18596,15-A5,Caturra,M0,NA,NA,0/0,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27752251,LOC113719066,Chr11e,NC_039919.1,42341115,15-C2,Catuai,M0,NA,NA,0/1,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,XR_003454739.1,pseudogene,0,NA
27752252,LOC113719066,Chr11e,NC_039919.1,42341115,15-D6,Caturra,M0,NA,NA,0/1,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,XR_003454739.1,pseudogene,0,NA
27752253,LOC113719066,Chr11e,NC_039919.1,42341115,16-C5,Catuai,M0,NA,NA,0/2,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,XR_003454739.1,pseudogene,0,NA
27752254,LOC113719066,Chr11e,NC_039919.1,42341115,16-D7,Catuai,M0,NA,NA,0/2,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,XR_003454739.1,pseudogene,0,NA
27752255,LOC113719066,Chr11e,NC_039919.1,42341115,16-E4,Catuai,M0,NA,NA,0/1,TGGGGGGGGGGGGAGAAGAGGAAAT,"TGGGGGGGGGGGAGAAGAGGAAAT,TGGGGGGGGGGGGGAGAAGAG...","del,ins",MODIFIER,non_coding_transcript_variant,XR_003454739.1,pseudogene,0,NA

In [30]:
master_final.to_csv('master_data.csv', index=False, header=True)

In [31]:
master_final[master_final['ANN[*].GENE'] == 'rpoC2']

,ANN[*].GENE,CHROM,CONTIG,POS,Sample_ID,Variety,Generation,Treatment,Dose,GT,REF,ALT,TYPE,ANN[*].IMPACT,ANN[*].EFFECT,ANN[*].FEATUREID,ANN[*].BIOTYPE,ANN[*].DISTANCE,ID
0,rpoC2,Chloroplast,NC_008535.1,18596,1-C7,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
1,rpoC2,Chloroplast,NC_008535.1,18596,1-D4,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
2,rpoC2,Chloroplast,NC_008535.1,18596,1-E2,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
3,rpoC2,Chloroplast,NC_008535.1,18596,1-E4,Venetia,M0,NA,NA,0/1,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
4,rpoC2,Chloroplast,NC_008535.1,18596,15-A5,Caturra,M0,NA,NA,0/0,CT,TC,complex,MODERATE,missense_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,0,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,rpoC2,Chloroplast,NC_008535.1,25804,15-C2,Catuai,M0,NA,NA,0/1,C,T,snp,MODIFIER,upstream_gene_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,4779,NA
3344,rpoC2,Chloroplast,NC_008535.1,25804,15-D6,Caturra,M0,NA,NA,0/1,C,T,snp,MODIFIER,upstream_gene_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,4779,NA
3345,rpoC2,Chloroplast,NC_008535.1,25804,16-C5,Catuai,M0,NA,NA,0/0,C,T,snp,MODIFIER,upstream_gene_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,4779,NA
3346,rpoC2,Chloroplast,NC_008535.1,25804,16-D7,Catuai,M0,NA,NA,0/1,C,T,snp,MODIFIER,upstream_gene_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,4779,NA
3347,rpoC2,Chloroplast,NC_008535.1,25804,16-E4,Catuai,M0,NA,NA,0/1,C,T,snp,MODIFIER,upstream_gene_variant,TRANSCRIPT_gene-CoarCp011,protein_coding,4779,NA